# Generated by Django 4.2.1 on 2023-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='lastname',
        ),
        migrations.AddField(
            model_name='userform',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Enter your name'),
        ),
    ]
